# Data Encoding

        1. Nominal/OHE Encoding
        2. Label and ordinal encoding
        3. Target guided ordinal encodng

            Nominal/OHE Encoding:
                technique used to represent categorical data to numerical data, which is more suitable for machine learning algorithm. Each cataegory represented as binary vector where each bit corresponds to a unique category.

                1. Red[1,0,0]
                2. Green[0,1,0]
                3. Blue[0,0,1]

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'blue', 'red']
})  

df.head()

   color
0    red
1   blue
2  green
3   blue
4    red

In [6]:
#create an insatnce of OneHotEncoder
encoder = OneHotEncoder()

In [7]:
# fit and transform the data
encoded_data = encoder.fit_transform(df[['color']]).toarray()
print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

In [10]:
encoder_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['color']))
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [11]:
#for new data
encoder.transform([['blue']]).toarray()

/Users/gyanendramohanpatel/Desktop/Data Analytics/venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])